### ISSUE TITLE
Epic for Alpha

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/hourglass#113]
**As a user I want to manage & time my tasks.**

_As a user I want to ..._
- [ ] create new tasks (cancel with esc) #114 
- [ ] delete tasks #41 
- [ ] mark tasks as complete #16 
- [ ] mark completed tasks as not completed #16 
- [ ] rename tasks #111 
- [ ] edit time #115
- [ ] priorities tasks #82 
- [ ] start/stop timing on tasks #77
- [ ] See the amount of tasks (count excludes archived) next to hourglass
- [ ] close the app by clicking on x
## Design for Alpha Version

![artboard 5](https://cloud.githubusercontent.com/assets/813754/3520232/4257f94e-072c-11e4-8fa3-677b3411d662.png)
